services:
  # ======================
  # Website
  # ======================
  - type: web
    name: flight-website
    env: node
    buildCommand: yarn install --production=false && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NODE_VERSION
        value: 22
    healthCheckPath: /
    plan: starter
